export const CHANGE_CONNECTION_STATUS = 'CHANGE_CONNECTION_STATUS';

export const FETCH_USER_LOGIN_REQUEST = 'FETCH_USER_LOGIN_REQUEST';
export const FETCH_USER_LOGIN_SUCCESS = 'FETCH_USER_LOGIN_SUCESS';
export const FETCH_USER_LOGIN_FAILED = 'FETCH_USER_LOGIN_FAILED';
export const SET_USER_LOGOUT = 'SET_USER_LOGOUT';

export const FETCH_TOKEN_REQUEST = 'FETCH_TOKEN_REQUEST';
export const FETCH_TOKEN_SUCCESS = 'FETCH_TOKEN_SUCCESS';
export const FETCH_TOKEN_FAILED = 'FETCH_TOKEN_FAILED';
export const RESTORE_TOKEN = 'RESTORE_TOKEN'
export const CLEAR_TOKEN = 'CLEAR_TOKEN'

export const FETCH_TASKS_REQUEST = 'FETCH_TASK_REQUEST';
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS';
export const FETCH_TASKS_FAILED = 'FETCH_TASKS_FAILED';

export const FETCH_TASK_FORM_REQUEST = 'FETCH_TASKS_FORM_REQUEST';
export const FETCH_TASK_FORM_SUCCESS = 'FETCH_TASK_FORM_SUCCESS';
export const FETCH_TASK_FORM_FAILED = 'FETCH_TASK_FORM_FAILED'; 